steps:
- task: DockerCompose@0
  displayName: Run SBT test
  inputs:
    dockerComposeCommand: |
      run --rm sbt test
- task: DockerCompose@0
  displayName: Package JAR
  inputs:
    dockerComposeCommand: |
      run --rm sbt assembly
- task: DockerCompose@0
  displayName: Copy to databricks
  inputs:
    dockerComposeCommand: |
      run --rm db databricks --help