steps:
- task: DockerCompose@0
  displayName: Run SBT test
  inputs:
    dockerComposeCommand: |
      run --rm sbt sbt test
- task: DockerCompose@0
  displayName: Package JAR
  inputs:
    dockerComposeCommand: |
      run --rm sbt sbt assembly
- task: DockerCompose@0
  displayName: Copy to databricks
  env:
    DATABRICKS_TOKEN: $(databricks_token)
    DATABRICKS_HOST: $(databricks_host)
  inputs:
    dockerComposeCommand: |
      run --rm db /mount/deploy.sh