version: "3.3"
services:
  sbt: 
    image: hseeberger/scala-sbt:latest
    volumes: 
     - type: bind 
       source: .
       target: /root
    tty: true
  db:
    image: timvancann/databricks-cli:latest
    volumes: 
      - type: bind 
        source: .
        target: /mount
    environment:
      - DATABRICKS_HOST
      - DATABRICKS_TOKEN
    tty: true