version: "3.2"
services:
  sbt: 
    image: hseeberger/scala-sbt:latest
    volumes: 
     - type: bind 
       source: .
       target: /root
  db:
    image: timvancann/databricks-cli:latest
    volumes: 
      - type: bind 
        source: .
        target: /mount
